version: '2'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_URL=<database ip>
      - DB_PORT=<database port>
      - DB_USERNAME=<database username>
      - DB_PASSWORD=<database password>
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '80:3000'
